// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRVpEqqti7Z4q14kqssLpOocVlFcaAbI',
    appId: '1:811391520731:web:78c48967394a02692ce1fe',
    messagingSenderId: '811391520731',
    projectId: 'todolist-6e96d',
    authDomain: 'todolist-6e96d.firebaseapp.com',
    storageBucket: 'todolist-6e96d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzhIVPgLPg2fH26Gy1mO8VnlKFRUJJI4',
    appId: '1:811391520731:android:04884f6c087edf942ce1fe',
    messagingSenderId: '811391520731',
    projectId: 'todolist-6e96d',
    storageBucket: 'todolist-6e96d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACH6MWZUWsauT0fhbTnLKcERr-haNy2X0',
    appId: '1:811391520731:ios:cde827998ed1e60f2ce1fe',
    messagingSenderId: '811391520731',
    projectId: 'todolist-6e96d',
    storageBucket: 'todolist-6e96d.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACH6MWZUWsauT0fhbTnLKcERr-haNy2X0',
    appId: '1:811391520731:ios:b4475d3fc886d2472ce1fe',
    messagingSenderId: '811391520731',
    projectId: 'todolist-6e96d',
    storageBucket: 'todolist-6e96d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYRVpEqqti7Z4q14kqssLpOocVlFcaAbI',
    appId: '1:811391520731:web:f11cd1932e1c06272ce1fe',
    messagingSenderId: '811391520731',
    projectId: 'todolist-6e96d',
    authDomain: 'todolist-6e96d.firebaseapp.com',
    storageBucket: 'todolist-6e96d.firebasestorage.app',
  );
}
